version: "2.2"
services:
  composer:
    restart: 'no'
    image: prooph/composer:7.4
    working_dir: /www/aggreagtion-api
    command: install --ignore-platform-reqs
    volumes:
      - ./sites/aggreagtion-api:/www/aggreagtion-api
  supervisor:
    build: ./services/supervisor
    container_name: supervisor
    restart: always
    volumes:
      - ./sites/aggreagtion-api:/www/aggreagtion-api
    depends_on:
      - composer
  php-fpm:
    build: ./services/php
    ports:
      - "9001:9000"
    container_name: php
    restart: always
    depends_on:
      - mysql
      - supervisor
    volumes:
      - ./sites/aggreagtion-api:/www/aggreagtion-api
  mysql:
    build: ./services/mysql
    ports:
      - "3307:3306"
    container_name: mysql
    restart: always
    command:
      [
        '--character-set-server=utf8mb4', #设置数据库表的数据集
        '--collation-server=utf8mb4_general_ci'
      ]
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
     image: redis:latest
     restart: unless-stopped
     container_name: redis
     ports:
       - "5070:6379"
     volumes:
       - ./services/redis/redis.conf:/etc/redis/redis.conf 
       - ./data/redis:/data      
     command: redis-server /etc/redis/redis.conf 

  nginx:
    build: ./services/nginx
    ports:
      - "81:80"
      - "83:81"
      - "444:443"
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ./sites/aggreagtion-api:/www/aggreagtion-api
      - ./sites/aggregation-admin:/www/aggregation-admin
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d:/etc/nginx/conf.d:rw
networks:
  default:
    external:
      name: aggegation-net
